complete build for telemed intake

diff --git a/.github/workflows/build-and-deploy-telemed-intake.yml b/.github/workflows/build-and-deploy-telemed-intake.yml
--- a/.github/workflows/build-and-deploy-telemed-intake.yml
+++ b/.github/workflows/build-and-deploy-telemed-intake.yml
@@ -1,5 +1,10 @@
 name: Deploy
 
+env:
+  CI: false
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
 on:
   workflow_dispatch:
     inputs:
@@ -48,6 +53,10 @@ jobs:
             ${{ secrets.OTTEHR_DEMO_PRIVATE_KEY }}
             ${{ secrets.BUMP_VERSION }}
 
+      - name: If environment is production, ensure keys are coming in through input parameters.
+        if: ${{ github.event.inputs.environment == 'production' && !(github.event.inputs.confirmProduction == 'Yes') }}
+        run: echo 'Please confirm you want to deploy to production.' && exit 1
+
       - uses: actions/checkout@v3
         with:
           ssh-key: ${{ secrets.BUMP_VERSION }}
@@ -60,6 +69,9 @@ jobs:
       - uses: pnpm/action-setup@v2
         with:
           version: 8
+
+      - name: Deploy App
+        run: pnpm telemed:deploy:${{ github.event.inputs.environment }}
 
       - name: Check out secrets repo to grab the env file.
         uses: actions/checkout@v3
@@ -106,33 +118,22 @@ jobs:
       - name: Deploy zambdas
         run: cd ${{ env.ZAMBDAS_LOCATION }} && pnpm deploy-zambdas:${{ github.event.inputs.environment }}
 
-      - name: Configure AWS CLI
-        uses: aws-actions/configure-aws-credentials@v1
+      - name: Notify Slack
+        if: always()
+        uses: edge/simple-slack-notify@v1.1.2
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          BRANCH: ${{ github.ref }}
+          PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-
-      - name: Deploy to AWS S3
-        run: |
-          aws s3 sync ./packages/telemed-intake/app/build s3://telemed.ottehr.com --delete
-
-      # - name: Notify Slack
-      #   if: always()
-      #   uses: edge/simple-slack-notify@v1.1.2
-      #   env:
-      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-      #     BRANCH: ${{ github.ref }}
-      #     PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
-      #   with:
-      #     channel: '#ottehr-notifications'
-      #     status: ${{ job.status }}
-      #     success_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy completed successfully'
-      #     failure_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy failed'
-      #     cancelled_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy was cancelled'
-      #     fields: |
-      #       [{ "title": "Service", "value": "${{ env.SLACK_NOTIFICATION_SERVICE_NAME }}", "short": true },
-      #       { "title": "Action URL", "value": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"},
-      #       { "title": "Branch", "value": "${{ env.BRANCH }}", "short": true },
-      #       { "title": "Environment", "value": "${{ env.ENVIRONMENT }}", "short": true },
-      #       { "title": "Version", "value": "${{ env.PACKAGE_VERSION }}", "short": true }]
+          channel: '#ottehr-notifications'
+          status: ${{ job.status }}
+          success_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy completed successfully'
+          failure_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy failed'
+          cancelled_text: '${{ env.GITHUB_WORKFLOW }} (Run #${{ env.GITHUB_RUN_NUMBER }}) deploy was cancelled'
+          fields: |
+            [{ "title": "Service", "value": "${{ env.SLACK_NOTIFICATION_SERVICE_NAME }}", "short": true },
+            { "title": "Action URL", "value": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"},
+            { "title": "Branch", "value": "${{ env.BRANCH }}", "short": true },
+            { "title": "Environment", "value": "${{ env.ENVIRONMENT }}", "short": true },
+            { "title": "Version", "value": "${{ env.PACKAGE_VERSION }}", "short": true }]
